describe("SORTING BALLS", function(){
    it("should produce a new object with empty array", function(){
        let newBalls = new Rack()
        expect(newBalls.balls).toEqual([])
    })
    it("should receive a number and add it to array", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        expect(newBalls.balls).toEqual([10])
    })
    it("should receive a new number and add it to array", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(20)
        expect(newBalls.balls).toEqual([10, 20])
    })
    it("should receive a new number and add it to array that is lower than the first one", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(5)
        let result  = newBalls.sort()
        expect(result).toEqual([5, 10])
    })
    it("should add 3 numbers to array and order them", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(5)
        newBalls.add(7)
        let result  = newBalls.sort()
        expect(result).toEqual([5, 7, 10])
    })
    it("should find the middle element of an array of 3", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(5)
        newBalls.add(7)
        let result  = newBalls.findMiddle()
        expect(result).toEqual(5)
    })
    it("should find the 1 element of an array of 2", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(5)
        // console.log(newBalls.balls)
        let result  = newBalls.findMiddle()
        expect(result).toEqual(5)
    })
    it("should sort an array of 2", function(){
        let newBalls = new Rack()
        newBalls.add(10)
        newBalls.add(5)
        let result  = newBalls.swap()
        expect(result).toEqual([5, 10])
    })
    it("should sort an array of 3", function(){
        let newBalls = new Rack()
        let leftIndex = 0
        newBalls.add(10)
        newBalls.add(5)
        newBalls.add(7)
        let result  = newBalls.middle()
        console.log("array = " + newBalls.balls)
        console.log("first index " + newBalls.balls[leftIndex])
        console.log("result = " + result)
        expect(result).toEqual(5)
    })
})